ARG PHP_VERSION="8.2-fpm-alpine"
ARG PHP_BASE_IMAGE="php:${PHP_VERSION}"
ARG PHP_COMPOSER_VERSION="2.7.7"
ARG NODE_VERSION="22.11-alpine"
ARG NODE_BASE_IMAGE="node:${NODE_VERSION}"

FROM ${NODE_BASE_IMAGE} AS node

FROM composer:${PHP_COMPOSER_VERSION} AS composer

FROM ${PHP_BASE_IMAGE} AS php-fpm-base

RUN apk add --update --no-cache \
    shadow \
    bash \
    && rm -rf /var/cache/apk/* /tmp/*

RUN chsh -s /bin/bash

# COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

COPY --from=composer /usr/bin/composer /usr/bin/composer

SHELL [ "/bin/bash", "-c" ]

ENTRYPOINT [ "/bin/bash" ]

# CMD [ "/bin/bash", "-c" ]
